### PR TITLE
updated VMAware to 1.5 format

### PR DESCRIPTION
**Pull request by kernelwernel**
I've made a [1.5 version](https://github.com/kernelwernel/VMAware/releases/tag/v1.5) of the VMAware library very recently, and I admittedly made a few mistakes which shouldn't had been done in prior releases. One of them was the unreliable and confusing format to disable techniques.

from:
```cpp
if (VM::detect(VM::DEFAULT & ~(static_cast < std::bitset<92>>(VM::GAMARUE)))) {
```

to:
```cpp
if (VM::detect(VM::DISABLE(VM::GAMARUE))) {
```

~~However, I haven't updated the `cmake/ports/vmaware/portfile.cmake` file to fetch the latest 1.5 content as I'm not sure how you got that SHA512 hash in the `vcpkg_from_github` function, which you will need to manually update.~~
EDIT: fixed

Also, is it possible if I can know why VM::GAMARUE is specifically disabled? Is there an error or a false positive associated with the technique?

Thanks in advance!

### CODE REVIEW

**Comment by qudix** [comment]
It's the SHA512 hash of the `tar.gz` archive of the specified git commit
`https://github.com/kernelwernel/VMAware/archive/<commit-hash-goes-here>.tar.gz`

**Comment by kernelwernel** [comment]
> It's the SHA512 hash of the `tar.gz` archive of the specified git commit `https://github.com/kernelwernel/VMAware/archive/<commit-hash-goes-here>.tar.gz`

Thanks! That helps a lot. I've updated the fetcher now.

**Comment by alandtse** [comment]
Oh thanks for this. I didn't get a notification for this. I'll go ahead and merge the disable change. Much more convenient then the bit thing.

**Comment by alandtse** [comment]
Ahh crap I went the wrong direction.

**Comment by kernelwernel** [comment]
> Oh thanks for this. I didn't get a notification for this. I'll go ahead and merge the disable change. Much more convenient then the bit thing.

the thing is that now it’s a 1.9 version instead of a 1.5, just a heads up

**Comment by alandtse** [comment]
Yah I made the update and the bit thing. Ok I really screwed this up editing it on the gui and forgot which direction the conflict was. I'm gonna close this and make the change directly, but thank you for the PR and also for the improvements to it.

**Comment by alandtse** [comment]
Oh, `VM::GAMARUE` was giving a false positive for a lot of crash logs so I disabled it. I can try to reenable it again and see if i'm still seeing it.

**Comment by kernelwernel** [comment]
> Yah I made the update and the bit thing. Ok I really screwed this up editing it on the gui and forgot which direction the conflict was. I'm gonna close this and make the change directly, but thank you for the PR and also for the improvements to it.

no problem, git and version control are also my worst nightmare lol

> Oh, `VM::GAMARUE` was giving a false positive for a lot of crash logs so I disabled it. I can try to reenable it again and see if i'm still seeing it.

i see. thanks for the input :)

**Pull request closed without merging**
